# Generated by Django 4.0.5 on 2022-06-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voltlines_app', '0002_passenger_registered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voltlines_app.passenger')),
            ],
        ),
    ]
